/*
 Navicat Premium Data Transfer

 Source Server         : oracle local
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1521
 Source Schema         : PS_BONDED_CUSTOMS

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 02/03/2022 10:14:39
*/


-- ----------------------------
-- Table structure for SYS_MENU
-- ----------------------------
DROP TABLE "PS_BONDED_CUSTOMS"."SYS_MENU";
CREATE TABLE "PS_BONDED_CUSTOMS"."SYS_MENU" (
  "MENU_ID" VARCHAR2(36 CHAR) NOT NULL,
  "MENU_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "MENU_TYPE" VARCHAR2(1 CHAR),
  "PARENT_ID" VARCHAR2(36 CHAR),
  "URI" VARCHAR2(255 CHAR),
  "ICON" VARCHAR2(255 CHAR),
  "SORT_NUM" NUMBER(7,0),
  "PERMISSION_CODE" VARCHAR2(50 CHAR),
  "SECURITY_LEVEL" VARCHAR2(1 CHAR),
  "CREATE_TIME" DATE,
  "UPDATE_TIME" DATE,
  "CREATE_USER" VARCHAR2(50 CHAR),
  "UPDATE_USER" VARCHAR2(50 CHAR),
  "DE_FLAG" VARCHAR2(1 CHAR)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."MENU_NAME" IS '菜单名';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."MENU_TYPE" IS '菜单类型(地址/按钮)';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."PARENT_ID" IS '父节点ID';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."URI" IS '地址';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."ICON" IS '图标';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."SORT_NUM" IS '序号';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."PERMISSION_CODE" IS '权限标识';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."SECURITY_LEVEL" IS '安全等级';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."CREATE_USER" IS '创建人';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."UPDATE_USER" IS '修改人';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_MENU"."DE_FLAG" IS '删除标识';

-- ----------------------------
-- Records of SYS_MENU
-- ----------------------------
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('1', '首页', '1', '0', '/', 'el-icon-house', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('2', '智能化数据展示板块', '1', '0', '/customsMap', 'el-icon-s-data', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('201', '综合信息总览', '1', '2', 'index', NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('202', '业务风险信息展示', '1', '2', 'busifenkong', NULL, '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('203', '业务车辆情况概览', '1', '2', 'vehicle', NULL, '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('204', '园区企业基本情况展示', '1', '2', 'enterprisePicture', NULL, '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('205', '重点业务运行情况概览', '1', '2', 'importantBusiness', NULL, '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('206', '风险分析管理规则设置', '1', '2', 'ruleType', NULL, '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('207', '业务车辆管理规则设置', '1', '2', 'statusAlert', NULL, '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('208', '园区街道企业数量管理', '1', '2', 'enterpriseNumberManagement', NULL, '8', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('209', '重点业务情况录入', '1', '2', 'businessInput', NULL, '9', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('20901', '超期报关单预警情况', '1', '209', 'kpiOverOrderWarn', NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('20902', '出口标准品整体通关时效情况', '1', '209', 'kpiOutProduct', NULL, '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('20903', '提前申报情况', '1', '209', 'kpiAdvanceApply', NULL, '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('20904', '区域监管情况', '1', '209', 'kpiAreaMonitor', NULL, '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('20905', '稽核查及审核处置', '1', '209', 'kpiAuditReview', NULL, '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('20906', '运控平台预警处置单统计', '1', '209', 'kpiControlOperation', NULL, '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('20907', '货物监管', '1', '209', 'kpiGoodMonitor', NULL, '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('20908', '进出口货物通关时效情况', '1', '209', 'kpiOutInProduct', NULL, '8', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('20909', '税收征管', '1', '209', 'kpiTaxManagement', NULL, '9', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('20910', '两步申报应用率情况', '1', '209', 'kpiTwoStepApply', NULL, '10', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('20911', '签证业务', '1', '209', 'kpiVisaBusiness', NULL, '11', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('3', '三方数据联动板块', '1', '0', '/approval', 'el-icon-s-check', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('301', '入驻申请审批', '1', '3', 'settleApply', NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('302', '资质申请审批', '1', '3', 'qualifications', NULL, '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('303', '新业务试点审批', '1', '3', 'newBusiness', NULL, '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('304', '创新业务审批', '1', '3', 'innovativeBusiness', NULL, '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('305', '企业信息上报审批', '1', '3', 'infoReport', NULL, '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('306', '预约申请审批', '1', '3', 'order', NULL, '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('307', '联合验仓审批', '1', '3', 'union', NULL, '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('308', '其他事项审批', '1', '3', 'other', NULL, '8', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('309', '企业申请统计分析', '1', '3', 'applyCount', NULL, '9', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('310', '企业申请综合查询', '1', '3', 'enterprise', NULL, '10', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('311', '企业运营信息上报记录', '1', '3', 'submitRecord', NULL, '11', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('312', '业务配置管理', '1', '3', 'configurationManagement', NULL, '12', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('31201', '资质类型设置', '1', '312', 'qualificationType', NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('31202', '申请事项设置', '1', '312', 'applyManagement', NULL, '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('31203', '审批路径设置', '1', '312', 'approvalPath', NULL, '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('31204', '试点业务设置', '1', '312', 'businessConfig', NULL, '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('4', '智慧化园区管理板块', '1', '0', '/dataGovernance', 'el-icon-notebook-1', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('401', '行政车辆出入园区记录', '1', '4', 'carsEnterOutStatistics', NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('402', '行政车辆备案记录', '1', '4', 'carsReception', NULL, '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('403', '车辆异常报警记录', '1', '4', 'carErrorCheck', NULL, '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('404', '货车出入园区记录统计分析', '1', '4', 'trunkEnterOutRecord', NULL, '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('405', '货车异常行为记录统计分析', '1', '4', 'trunkWrongRecord', NULL, '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('406', '全景实时状态展示', '1', '4', 'realTime', NULL, '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('407', '重点区域设置', '1', '4', 'importantSetting', NULL, '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('5', '系统信息管理', '1', '0', '/logManagement', 'el-icon-s-tools', '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('501', '日志管理', '1', '5', 'log', NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('502', '字典管理', '1', '5', 'dictionaries', NULL, '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('503', '安全管理', '1', '5', 'kpiManage', NULL, '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('50101', '系统日志记录', '1', '501', 'system', NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('50102', '操作日志记录', '1', '501', 'operate', NULL, '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "PS_BONDED_CUSTOMS"."SYS_MENU" VALUES ('50103', '报文日志记录', '1', '501', 'message', NULL, '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- ----------------------------
-- Primary Key structure for table SYS_MENU
-- ----------------------------
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_MENU" ADD CONSTRAINT "SYS_C0011939" PRIMARY KEY ("MENU_ID");

-- ----------------------------
-- Checks structure for table SYS_MENU
-- ----------------------------
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_MENU" ADD CONSTRAINT "SYS_C0011937" CHECK ("MENU_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_MENU" ADD CONSTRAINT "SYS_C0011938" CHECK ("MENU_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_MENU" ADD CONSTRAINT "SYS_C0013885" CHECK ("MENU_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_MENU" ADD CONSTRAINT "SYS_C0013886" CHECK ("MENU_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_MENU" ADD CONSTRAINT "SYS_C0014984" CHECK ("MENU_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_MENU" ADD CONSTRAINT "SYS_C0014985" CHECK ("MENU_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_MENU" ADD CONSTRAINT "SYS_C0015238" CHECK ("MENU_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_MENU" ADD CONSTRAINT "SYS_C0015239" CHECK ("MENU_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
