/*
 Navicat Premium Data Transfer

 Source Server         : oracle local
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1521
 Source Schema         : PS_BONDED_CUSTOMS

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 02/03/2022 10:15:01
*/


-- ----------------------------
-- Table structure for SYS_USER
-- ----------------------------
DROP TABLE "PS_BONDED_CUSTOMS"."SYS_USER";
CREATE TABLE "PS_BONDED_CUSTOMS"."SYS_USER" (
  "USER_ID" VARCHAR2(36 CHAR) NOT NULL,
  "USERNAME" VARCHAR2(50 CHAR) NOT NULL,
  "PASSWORD" VARCHAR2(255 CHAR) NOT NULL,
  "SALT" VARCHAR2(255 CHAR),
  "ACCOUNT" VARCHAR2(50 CHAR) NOT NULL,
  "PHONE" VARCHAR2(25 CHAR),
  "EMAIL" VARCHAR2(120 CHAR),
  "STATUS" VARCHAR2(1 CHAR),
  "VALID_TIME" DATE,
  "ROLE_ID" VARCHAR2(36 CHAR) NOT NULL,
  "CREATE_TIME" DATE,
  "UPDATE_TIME" DATE,
  "CREATE_USER" VARCHAR2(50 CHAR),
  "UPDATE_USER" VARCHAR2(50 CHAR),
  "DE_FLAG" VARCHAR2(1 CHAR),
  "BONDED_CODE" VARCHAR2(50 CHAR)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."USERNAME" IS '用户名';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."SALT" IS '密钥';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."ACCOUNT" IS '账户';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."PHONE" IS '手机';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."STATUS" IS '状态';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."VALID_TIME" IS '有效期';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."ROLE_ID" IS '角色';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."CREATE_USER" IS '创建人';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."UPDATE_USER" IS '修改人';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."DE_FLAG" IS '删除标识';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_USER"."BONDED_CODE" IS '保税区编号';

-- ----------------------------
-- Records of SYS_USER
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table SYS_USER
-- ----------------------------
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0011548" PRIMARY KEY ("USER_ID");

-- ----------------------------
-- Checks structure for table SYS_USER
-- ----------------------------
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0011545" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0011546" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0011547" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0011553" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0011795" CHECK ("ACCOUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0011849" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0011850" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0011851" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0011852" CHECK ("ACCOUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0011853" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0013892" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0013893" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0013894" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0013895" CHECK ("ACCOUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0013896" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0014993" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0014994" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0014995" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0014996" CHECK ("ACCOUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0014997" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0015247" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0015248" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0015249" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0015250" CHECK ("ACCOUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_USER" ADD CONSTRAINT "SYS_C0015251" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
