/*
 Navicat Premium Data Transfer

 Source Server         : oracle local
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1521
 Source Schema         : PS_BONDED_CUSTOMS

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 02/03/2022 10:15:23
*/


-- ----------------------------
-- Table structure for SYS_ROLE
-- ----------------------------
DROP TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE";
CREATE TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE" (
  "ROLE_ID" VARCHAR2(36 CHAR) NOT NULL,
  "ROLE_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "DESCRIBE" VARCHAR2(255 CHAR),
  "CREATE_TIME" DATE,
  "UPDATE_TIME" DATE,
  "CREATE_USER" VARCHAR2(50 CHAR),
  "UPDATE_USER" VARCHAR2(50 CHAR),
  "DE_FLAG" VARCHAR2(1 CHAR)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_ROLE"."ROLE_NAME" IS '角色名称';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_ROLE"."DESCRIBE" IS '角色说明';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_ROLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_ROLE"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_ROLE"."CREATE_USER" IS '创建人';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_ROLE"."UPDATE_USER" IS '修改人';
COMMENT ON COLUMN "PS_BONDED_CUSTOMS"."SYS_ROLE"."DE_FLAG" IS '删除标识';

-- ----------------------------
-- Records of SYS_ROLE
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table SYS_ROLE
-- ----------------------------
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE" ADD CONSTRAINT "SYS_C0011525" PRIMARY KEY ("ROLE_ID");

-- ----------------------------
-- Checks structure for table SYS_ROLE
-- ----------------------------
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE" ADD CONSTRAINT "SYS_C0011523" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE" ADD CONSTRAINT "SYS_C0011524" CHECK ("ROLE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE" ADD CONSTRAINT "SYS_C0011844" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE" ADD CONSTRAINT "SYS_C0011845" CHECK ("ROLE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE" ADD CONSTRAINT "SYS_C0013887" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE" ADD CONSTRAINT "SYS_C0013888" CHECK ("ROLE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE" ADD CONSTRAINT "SYS_C0014988" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE" ADD CONSTRAINT "SYS_C0014989" CHECK ("ROLE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE" ADD CONSTRAINT "SYS_C0015242" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PS_BONDED_CUSTOMS"."SYS_ROLE" ADD CONSTRAINT "SYS_C0015243" CHECK ("ROLE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
